import CutLayout from "./CutLayout.js";

let neededDimmensions = [
    { reference: 'Salon 1', length: 141 },
    { reference: 'Salon  2', length: 37 },
    { reference: 'Salon 3', length: 156 },
    { reference: 'Salon 4', length: 37 },
    { reference: 'Salon  5', length: 235 },
    { reference: 'Salon 6', length: 495 },
    { reference: 'Salon 7', length: 7 },
    { reference: 'Salon  8', length: 12 },
    { reference: 'Salon 9', length: 427 },
    { reference: 'Mały korytarz 1', length: 84 },
    { reference: 'Mały korytarz 2', length: 33 },
    { reference: 'Mały korytarz 3', length: 90 },
    { reference: 'Mały korytarz 4', length: 100 },
    { reference: 'Mały korytarz 5', length: 6 },
    { reference: 'Mały korytarz 6', length: 49 },
    { reference: 'Wiatrołap 1', length: 45 },
    { reference: 'Wiatrołap 2', length: 70 },
    { reference: 'Wiatrołap 3', length: 30 },
    { reference: 'Wiatrołap 4', length: 10 },
    { reference: 'Wiatrołap 5', length: 212 },
    { reference: 'Wiatrołap 6', length: 35 },
    { reference: 'Wiatrołap 7', length: 35 },
    { reference: 'Wiatrołap 8', length: 105 },
    { reference: 'Wiatrołap 9', length: 95 },
    { reference: 'Korytarz 1', length: 4 },
    { reference: 'Korytarz 2', length: 50 },
    { reference: 'Korytarz 3', length: 18 },
    { reference: 'Korytarz 4', length: 19 },
    { reference: 'Korytarz 5', length: 10 },
    { reference: 'Sypialnia 1', length: 61 },
    { reference: 'Sypialnia 2', length: 17 },
    { reference: 'Sypialnia 3', length: 34 },
    { reference: 'Sypialnia 4', length: 362 },
    { reference: 'Sypialnia 5', length: 358 },
    { reference: 'Sypialnia 6', length: 368 },
    { reference: 'Sypialnia 7', length: 27 },
    { reference: 'Sypialnia 8', length: 130 },
    { reference: 'Sypialnia 9', length: 64 },
    { reference: 'Sypialnia Podwórko 1', length: 264 },
    { reference: 'Sypialnia Podwórko 2', length: 439 },
    { reference: 'Sypialnia Podwórko 3', length: 374 },
    { reference: 'Sypialnia Podwórko 4', length: 394 },
    { reference: 'Sypialnia Podwórko 5', length: 32 },
    { reference: 'Sypialnia Podwórko 6', length: 48 },
    { reference: 'Sypialnia Podwórko 7', length: 45 },
    { reference: 'Korytarz piętro 1', length: 13 },
    { reference: 'Korytarz piętro 2', length: 65 },
    { reference: 'Korytarz piętro 3', length: 180 },
    { reference: 'Korytarz piętro 4', length: 20 },
    { reference: 'Korytarz piętro 5', length: 47 },
    { reference: 'Korytarz piętro 6', length: 179 },
    { reference: 'Korytarz piętro 7', length: 42 },
    { reference: 'Korytarz piętro 8', length: 42 },
    { reference: 'Korytarz piętro 9', length: 64 },
    { reference: 'Korytarz piętro 10', length: 46 },
    { reference: 'Sypialnia Dziekońska 1', length: 270 },
    { reference: 'Sypialnia Dziekońska 2', length: 434 },
    { reference: 'Sypialnia Dziekońska 3', length: 272 },
    { reference: 'Sypialnia Dziekońska 4', length: 282 },
    { reference: 'Sypialnia Dziekońska 5', length: 138 },
    { reference: 'Sypialnia Dziekońska 6', length: 155 },
    { reference: 'Sypialnia Dziekońska 7', length: 48 },
    { reference: 'Gabinet 1', length: 181 },
    { reference: 'Gabinet 2', length: 242 },
    { reference: 'Gabinet 3', length: 340 },
    { reference: 'Gabinet 4', length: 242 },
    { reference: 'Gabinet 5', length: 65 },
];
let cutLostDimmension = 1;
let initialSlatLength = 260;

let debug = false;

let cutLayoutResult = new CutLayout(neededDimmensions, initialSlatLength, cutLostDimmension, debug);
cutLayoutResult.generateLayout();
cutLayoutResult.printTabular();
cutLayoutResult.printPrintable();
